version: "3.3"

services:
  server-api:
    build: ./server
    restart: always
    working_dir: /usr/src/app
    command: bash -c "yarn && yarn run dev"
    volumes:
      - ./server:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - server
      - client

  client-app:
    stdin_open: true
    build: ./client
    restart: always
    working_dir: /usr/src/app
    command: bash -c "yarn && yarn start"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - server-api
    ports:
      - 3000:3000
    networks:
      - client

networks:
  server:
  client: